name: ai_design_inspiration_hub
description: A macOS desktop application for managing UI design inspiration with MCP server integration for AI agents.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Native macOS UI
  macos_ui: ^2.0.0
  
  # Database
  sqflite_common_ffi: ^2.3.0
  
  # File system and paths
  path_provider: ^2.1.0
  path: ^1.8.3
  
  # UUID generation
  uuid: ^4.0.0
  
  # Image processing
  image: ^4.1.0
  
  # Menubar integration
  tray_manager: ^0.2.0
  window_manager: ^0.3.0
  
  # State management
  provider: ^6.1.0
  
  # Preferences
  shared_preferences: ^2.2.0
  
  # File picker
  file_picker: ^6.0.0
  
  # HTTP for MCP server
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  
  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

macos:
  generate: true