name: ai_design_inspiration_hub
description: A macOS-focused Flutter app for organizing UI screenshots and serving design specs via MCP.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  macos_ui: ^2.0.5
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  tray_manager: ^0.2.3
  flutter_riverpod: ^2.5.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/icons/
